lib = File.expand_path("lib", __dir__)
$LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib)
require 'fastlane/plugin/forsis/version'

Gem::Specification.new do |spec|
  spec.name          = 'fastlane-plugin-forsis'
  spec.version       = Fastlane::Forsis::VERSION
  spec.author        = 'Azadeh Bagheri'
  spec.email         = 'Azadeh.Bagheri@loblaw.ca'

  spec.summary       = 'This plugin produces generic test execution reports supported by SonarQube from JUnit test reports generated by fastlane.'
  spec.homepage      = "https://github.com/azohra/forsis"
  spec.license       = "MIT"
  spec.metadata      = {
    "bug_tracker_uri" => "https://github.com/azohra/forsis/issues",
    "changelog_uri" => "https://github.com/azohra/forsis/releases",
    "homepage_uri" => spec.homepage,
    "source_code_uri" => "https://github.com/azohra/forsis"
  }
  spec.files         = Dir["lib/**/*"] + %w(README.md LICENSE)
  spec.test_files    = spec.files.grep(%r{^(test|spec|features)/})
  spec.require_paths = ['lib']
  spec.required_ruby_version = '>= 2.5'

  # Don't add a dependency to fastlane or fastlane_re
  # since this would cause a circular dependency

  spec.add_dependency('nokogiri', '>= 1.13.2')

  spec.add_development_dependency('bundler', '>= 1.15.0', '< 3.0.0')
  spec.add_development_dependency('fastlane', '~> 2.185')
  spec.add_development_dependency('pry')
  spec.add_development_dependency('rake')
  spec.add_development_dependency('rspec', '~> 3.10')
  spec.add_development_dependency('rspec_junit_formatter')
  spec.add_development_dependency('rubocop', '~> 1.24')
  spec.add_development_dependency('rubocop-rake')
  spec.add_development_dependency('rubocop-rspec')
  spec.add_development_dependency('simplecov', '~> 0.21.2')
end
